[package]
name = "genetic_algorithm_test"
version = "0.1.0"
authors = ["Alexey <rnr-x@ya.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rand = "0.7"
rayon = "1.1"
serde_json = "1.0"